# Generated by Django 4.1.2 on 2022-10-16 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_mpesapayment_type_mpesacallbacks_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapayment',
            name='type',
            field=models.TextField(default=datetime.datetime(2022, 10, 16, 8, 20, 50, 188802, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
