# Generated by Django 4.1.2 on 2022-10-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_mpesapayment_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['created_at'], name='payments_mp_created_7970aa_idx'),
        ),
    ]
